### ISSUE TITLE
Has* methods should not throw exceptions

### ISSUE THREAD

**Issue by shadowhand** [lukasoppermann/http-status#16]
Having to write this is really weird:

``` php
try {
    $this->http->hasStatusCode($code);
} catch (\InvalidArgumentException $e)
    // does not exist
}
```

I would expect any method with a `has` prefix to always return a boolean and not to throw an exception:

``` php
if (!$this->http->hasStatusCode($code)) {
    $code = $default;
}
```

Seems like a much more elegant solution to me.

**Comment by colinodell** [comment]
+1

**Comment by lukasoppermann** [comment]
Hmm, does sound sensible, I will work on this in the coming days, thanks for the feedback.
