### ISSUE TITLE
the HttpStatus::code can produce erroneous response

### ISSUE THREAD

**Issue by nyamsprod** [lukasoppermann/http-status#2]
let's say you have the following code:

``` php
$httpStatus = new HttpStatus([23 => 'foo', 24 => 'foo', 25 => 'foo']);
$res = $httpStatus->code('foo');
```

I would expect `$res` to contain `[23, 24, 25]` but it returns `23`. So unless you enforce that each reason phrase must be unique, the `HttpStatus::code` method must return an `array` to normalize its return type.

**Comment by lukasoppermann** [comment]
True, I think enforcing a 1 to 1 relationship is the best idea here, as I see no valid use case the same message being used for a single code.

**Comment by lukasoppermann** [comment]
Fixed in https://github.com/lukasoppermann/http-status/commit/2ba3be4f284f11c815b9d8fe24cdfa133a61d2bf now you can only provide unique reason phrases. This will be available in `0.9.4`

**Comment by nyamsprod** [comment]
I think you made a mistake in your implementation:
https://github.com/lukasoppermann/http-status/blob/master/src/Httpstatus.php#L173
The check must not be done on the ``filterCollection` method but on the `mergeHttpStatus` method. Since this check must be made on every insert of the collection.

I would have done something like this

``` php
    public function mergeHttpStatus($code, $text)
    {
        $code = $this->filterHttpStatusCode($code);
        $text = trim($this->filterReasonPhrase($text));
        if ($this->hasReasonPhrase($text)) {
            throw new RuntimeException('The submitted reason phrase is already present in the collection');
        }

        $this->httpStatus[$code] = $text;
    }
```

Maybe the text trimming could be done in the filterReasonPhrase method to simplify the code even more :)

**Comment by lukasoppermann** [comment]
Hmm, the trim was actually a duplicate in any case since it was already in the `filterReasonPhrase` as well.

I had an implementation similar to yours in the beginig, but it would lead to errors when changing messages, like this:

```
[
  100 => 'Not Found',
  101 => 'Continue',
]
```

**Comment by nyamsprod** [comment]
Test Cases:

#### 1-a

``` php
$httpStatus = new Httpstatus();
$httpStatus->mergeHttpStatus(100, 'Continue'); //this should pass
```

#### 1-b
- same as 1-a but with a custom status code

``` php
$httpStatus = new Httpstatus();
$httpStatus->mergeHttpStatus(600, 'foo'); //this should pass
$httpStatus->mergeHttpStatus(600, 'foo'); //this should pass
```

#### 2-a

``` php
$httpStatus = new Httpstatus();
$httpStatus->mergeHttpStatus(100, 'Processing'); //this should failed
```

#### 2-b
- same as 2-a but with a custom status code

``` php
$httpStatus = new Httpstatus();
$httpStatus->mergeHttpStatus(600, 'foo'); //this should pass
$httpStatus->mergeHttpStatus(601, 'foo'); //this should failed
```

#### 2-c
- same as 2-a but with a mixed custom status code

``` php
$httpStatus = new Httpstatus();
$httpStatus->mergeHttpStatus(600, 'foo'); //this should pass
$httpStatus->mergeHttpStatus(200, 'foo'); //this should failed
```

The modified method to pass these tests

``` php
public function mergeHttpStatus($code, $text)
{
    $code = $this->filterHttpStatusCode($code);
    $text = $this->filterReasonPhrase($text);
    if ($this->hasReasonPhrase($text) && $this->getStatusCode($text) !== $code) {
        throw new RuntimeException('The submitted reason phrase is already present in the collection');
    }

    $this->httpStatus[$code] = $text;
}
```

**Comment by lukasoppermann** [comment]
Thanks, I updated it, now to overwrite one must simple stick to the correct order and change the existing text first, e.g.

``` php
[
  200 => 'Pretty Good',
  102 => 'OK',
]
```
