### ISSUE TITLE
Is this still maintained

### ISSUE THREAD

**Issue by Herz3h** [lukasoppermann/http-status#22]
Hello,

I would like to contribute localized http status codes, at least for French language. If I create a pull request will it get merged/updated on packagist ?

**Comment by lukasoppermann** [comment]
Yes it is. So generally yes. However I would currently not know how exactly this should be implemented. The reason phrases are part of th Standard Definition. What is your exact use case for a translated version ?

**Comment by Herz3h** [comment]
I want to show error messages to the end user using the http status codes, but need them to be translated.

**Comment by lukasoppermann** [comment]
Okay, so why can't you just use the configuration? https://github.com/lukasoppermann/http-status#configure

Wouldn't that very easily solve your issue?

**Comment by Herz3h** [comment]
Thought it would be useful to have messages already translated for future users. So they don't have to re-translate every http status code.

**Comment by lukasoppermann** [comment]
Hey @Herz3h as long as it is complete and does not change the default behavior of the package I am fine with the addition.

Maybe a `languages` folder could be added with files that can be loaded and inserted (just like the array) to use a specific language. What do you think?

**Comment by Herz3h** [comment]
I went ahead and created a folder `languages` as you suggested. But have some issues with tests not running (namespace problems). 

I'm not very familiar with phpunit, tried to add test file for french, but not sure what would be a good way to test all languages.

If you dont mind looking into, it's available on https://github.com/Herz3h/http-status

**Comment by lukasoppermann** [comment]
Hey @Herz3h can you please quickly rebase your branch. I will check it out afterwards. Thanks.

**Comment by Herz3h** [comment]
I rebased my branch 👍

**Comment by Herz3h** [comment]
Did you have time to look into it ? I've tried fixing it again, no success :/

**Comment by lukasoppermann** [comment]
Hey, I have a hard time finding the issue (I am not working with PHP anymore for some years). Can you send this as a PR so I can easily see the changes you made?

**Comment by Herz3h** [comment]
I've sent the pr. I usually work with symfony, so all this namespacing stuff is preconfigured, hence why I'm not very familiar with it.

**Comment by lukasoppermann** [comment]
Hey, so a couple things:

1. Move the `languages` folder into the `src` folder
2. In `Httpstatus.php` replace line 287 `$langClass = new $language;` with

```php
        $languageClassNamespace = 'Lukasoppermann\\Httpstatus\\languages\\'.$language;
        $langClass = new $languageClassNamespace();
```

This should make it work and allow you to add tests to verify that it is now working with both languages.

**Comment by Herz3h** [comment]
Amazing, that worked @lukasoppermann. I've pushed the changes including tests for french.
