### ISSUE TITLE
Fix phpunit config for php 7+

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/http-status#24]
There seems to be some issue which is why the tests are not run on php 7+

**Comment by Herz3h** [comment]
According to [this](https://phpunit.de/supported-versions.html), phpunit 4 is not really compatible with php 7.x. It needs to be updated to v5 at least.

**Comment by lukasoppermann** [comment]
No, it isn't you are correct, this is why I will move the supported php version to 7.3 (#25). I think it may make sense to include your PR only in the new version (sorry for the previous change). What do you think?

If so I will merge my PR and you would need to rebase again.

**Comment by Herz3h** [comment]
Sure, it's probably better to upgrade the version to php 7 as older versions aren't really supported anymore. 

I don't mind fixing my pr again :)
