### ISSUE TITLE
renaming the class public methods

### ISSUE THREAD

**Issue by nyamsprod** [lukasoppermann/http-status#3]
Currently the public method do not follow the RFC names so they convey some ambiguity. It would be better IMHO if you could rename accordingly:
- `HttpStatus::code` to `HttpStatus::getStatusCode($text)`
- `HttpStatus::text` to `HttpStatus::getReasonPhrase($code)`

**Comment by lukasoppermann** [comment]
This is changed in https://github.com/lukasoppermann/http-status/commit/0ccae3ce6c762c95477f608b9ec66a02bb419bcf and will be available in `0.9.4`. Thanks.
