### ISSUE TITLE
Make the class behave like a Collection Class

### ISSUE THREAD

**Issue by nyamsprod** [lukasoppermann/http-status#4]
Since `HttpStatus::code` and `HttpStatus::text` can throw exceptions it would be nice to have the following complementary methods:
- `HttpStatus::hasCode($code)` Tell whether the code exists in the collection
- `HttpStatus::hasReasonPhrase($text)` Tell whether the text exists in the collection
- make the collection implements the `countable` and `iteratorAggregates` interface.
- add a `HttpStatus::filter` method to create a new Collection based on the current one.
- add a `HttpStatus::merge` method to merge 2  or more `HttpStatus` objects.

These additions would make the Class a solid collection.

**Comment by lukasoppermann** [comment]
Hmm, this seems reasonable, I will look into it, thanks.

**Comment by lukasoppermann** [comment]
Hey @nyamsprod I implemented the first 2 suggestions, as I see their helpfulness for the project. I am however not quite sure about the `filter` and `merge` methods.

Could you please elaborate on why they would be useful and how they would work?

**Comment by nyamsprod** [comment]
Yep after thinking about it the last two filter and merge do not make any sense :+1: I thought the collection could change the $httpStatus by reducing its size. But that is not possible so the filter and merge method do not make any sense so I won't object on not implementing them

**Comment by lukasoppermann** [comment]
Okay, thanks for all the feedback. :+1:
