### ISSUE TITLE
Hyper Text Coffee Pot Control Protocol

### ISSUE THREAD

**Issue by coreyworrell** [lukasoppermann/http-status#5]
I don't see a whole lot of value to this library unless you add this
https://tools.ietf.org/html/rfc7168#section-2.3.1

Status code 418 - "I'm a teapot" is of most importance.

:sarcasm: :wink:

**Comment by lukasoppermann** [comment]
This is definitely a valid idea and I had been thinking about implementing it for a while, but I decided against it due to the extremely rare availability of tea pots that actually support the `coffee:` schema. 

This is definitely not worth the estimated 50% additional maintenance cost.

**Comment by coreyworrell** [comment]
Probably a good decision. Maybe revisit in 2050? haha.

Anyways, helpful class btw, thanks!
